
CREATE TABLE t_p37278024_kids_event_crm.orders (
  id SERIAL PRIMARY KEY,
  manager_id INTEGER REFERENCES t_p37278024_kids_event_crm.users(id),
  prepayment_screenshot TEXT,
  event_date DATE,
  event_time TIME,
  programs TEXT,
  program_duration VARCHAR(100),
  extra_program VARCHAR(255),
  hero VARCHAR(255),
  address_region VARCHAR(100),
  address_city VARCHAR(100),
  address_street VARCHAR(200),
  address_house VARCHAR(50),
  children_count INTEGER,
  children_age VARCHAR(100),
  birthday_name VARCHAR(100),
  birthday_age VARCHAR(50),
  notes TEXT,
  birthday_info TEXT,
  total_cost DECIMAL(10,2) DEFAULT 0,
  travel_cost DECIMAL(10,2) DEFAULT 0,
  total_sum DECIMAL(10,2) DEFAULT 0,
  prepayment DECIMAL(10,2) DEFAULT 0,
  remainder DECIMAL(10,2) DEFAULT 0,
  client_phone VARCHAR(20),
  client_name VARCHAR(100),
  animator_name VARCHAR(100),
  animator_title VARCHAR(100),
  commission_pct DECIMAL(5,2) DEFAULT 40,
  assistant_name VARCHAR(100),
  hero_photo TEXT,
  commission_amount DECIMAL(10,2) DEFAULT 0,
  status VARCHAR(50) DEFAULT 'active',
  created_at TIMESTAMP DEFAULT NOW()
);
